source "https://rubygems.org/"

gem 'activerecord', '~> 7.0', '>= 7.0.4.2'

gem 'rake', '~> 13.0', '>= 13.0.6'

gem "sinatra", "~> 2.1"

gem 'bcrypt', '~> 3.1', '>= 3.1.18'

gem "thin", "~> 1.8"
gem 'puma', '~> 6.3'

gem 'sqlite3', '~> 1.6', '>= 1.6.1'

gem "sinatra-activerecord"

gem 'require_all', '~> 3.0'

group :development do
  gem "rerun"
  gem "pry"

  gem "faker", "~> 2.18"
end